server:
  port: 8080
spring:
  application:
    name: "autenticaciones"
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/sjbd
    username: postgres
    password: admin
  sql:
    init:
      mode: always
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
intraron:
  security:
    jwt:
      secret-key: "d5a3c2e1f4b5a6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1" # Clave base64
      expiration-in-ms: 900000 # 15 minutos
  internal:
    service-api-key: "0c0e78f65e2b4f9a8d1c9e4a3c2b1a0f9e8d7c6b5a4d3e2f1g9h8i7j6k5l4m3n"
